//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blankspaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEDEPERSONA
    {
        public int IDDETALLE { get; set; }
        public string IDPERSONA { get; set; }
        public string LUGARDEESTUDIOS { get; set; }
        public Nullable<bool> TRABAJA { get; set; }
        public Nullable<bool> ESTUDIA { get; set; }
        public string NOMBREMADRE { get; set; }
        public string NOMBREPADRE { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
