//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blankspaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENALIZACION
    {
        public int IDPE { get; set; }
        public string ID { get; set; }
        public System.DateTime FECHAINI { get; set; }
        public System.DateTime FECHAFIN { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
